default:
  image: golang:1.19

stages:
  - build
  - publish

build:
  stage: build
  script:
    - make build-within-docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == $CAPVCD_RELEASE_BRANCH
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual

publish:
  stage: publish
  image:
    name: docker:20.10.16
    pull_policy: if-not-present
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$HARBOR_USER" -p "$HARBOR_AUTH" harbor-repo.vmware.com
  script:
    - apk add --update make git bash go curl
    - make kustomize
    - make dev
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == $CAPVCD_RELEASE_BRANCH
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
