apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VCDClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: vcdclustertemplate
    app.kubernetes.io/instance: vcdclustertemplate-sample
    app.kubernetes.io/part-of: cluster-api-provider-cloud-director
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-cloud-director
  name: vcdclustertemplate-sample
spec:
  # TODO(user): Add fields here
